# Materials {.unnumbered}

In this section, we provide a list of materials that can be useful for learning how to use the [`{tidyverse}`](https://www.tidyverse.org/), and how to create Shiny applications.

## Tidyverse

-   Book [R for Data Science](https://r4ds.hadley.nz/), by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund.

## Shiny

-   Tutorial [Shiny for R](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/), by Posit.

-   Book [Mastering Shiny](https://mastering-shiny.org/), by Hadley Wickham.

-   Book [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/), by Colin Fay, Sébastien Rochette, Vincent Guyader and Cervan Girard.

-   Gallery [Shiny components (inputs, outputs, messages)](https://shiny.posit.co/r/components/), by Posit.

-   Gallery [Nicer-looking Shiny widgets](https://dreamrs.github.io/shinyWidgets/), by Victor Perrier, Fanny Meyer, and David Granjon.

-   AI Assistant [Shiny AI assistant](https://gallery.shinyapps.io/assistant/), by Posit.

-   UI editor [Shiny UI editing tool](https://rstudio.github.io/shinyuieditor/), by Posit.


## Building modern dashboards

-  [Quarto dashboards **with** Shiny](https://quarto.org/docs/dashboards/interactivity/shiny-r.html)

-  [Quarto dashboards **without** Shiny](https://quarto.org/docs/dashboards/)

-  [Structuring dashboards with `{bslib}`](https://rstudio.github.io/bslib/articles/dashboards/index.html)

-  [Theming Shiny apps and dashboards with `{bslib}`](https://rstudio.github.io/bslib/articles/theming/index.html)

-  [Auto theming of plots with `{thematic}`](https://rstudio.github.io/thematic/index.html)


## Interactive mapping

-  [Creating interactive maps with `{leaflet}`](https://rstudio.github.io/leaflet/)

-  [Using Leaflet with Shiny](https://rstudio.github.io/leaflet/articles/shiny.html)

-  [Extensions for Leaflet with `{leafem}`](https://r-spatial.github.io/leafem/)

-  [Quick and convenient interactive maps with `{mapview}`](https://r-spatial.github.io/mapview/index.html)